/**
 * Export analysis to PDF and share (expo-print + expo-sharing)
 */

import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

function escapeHtml(s) {
  if (s == null) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/\n/g, '<br/>');
}

function buildHtml(analysis) {
  const a = analysis || {};
  const title = a.documentType || 'Document Analysis';
  const score = Math.min(100, Math.max(0, Number(a.score) || 0));
  const summary = a.summary || '';
  const parties = Array.isArray(a.parties) ? a.parties : [];
  const contractAmount = a.contractAmount ?? '';
  const payments = Array.isArray(a.payments) ? a.payments : [];
  const keyDates = Array.isArray(a.keyDates) ? a.keyDates : [];
  const redFlags = Array.isArray(a.redFlags) ? a.redFlags : [];
  const guidance = Array.isArray(a.guidance) ? a.guidance : [];

  const scoreColor = score >= 70 ? '#22c55e' : score >= 50 ? '#eab308' : '#ef4444';

  let partiesHtml = parties.map((p) => `<tr><td>${escapeHtml(p.name)}</td><td>${escapeHtml(p.role)}</td></tr>`).join('');
  let paymentsHtml = payments.map((p) => `<tr><td>${escapeHtml(p.label)}</td><td>${escapeHtml(p.amount)}</td></tr>`).join('');
  let keyDatesHtml = keyDates.map((d) => `<tr><td>${escapeHtml(d.date)}</td><td>${escapeHtml(d.label)}</td></tr>`).join('');
  let redFlagsHtml = redFlags
    .map(
      (r) =>
        `<div class="block"><strong>${escapeHtml(r.title || '')}</strong> (${escapeHtml(r.type || r.severity || '')})<br/>
        <em>Why this matters:</em> ${escapeHtml(r.whyMatters || '')}<br/>
        <em>What to do:</em> ${escapeHtml(r.whatToDo || '')}</div>`
    )
    .join('');
  let guidanceHtml = guidance
    .map((g) => `<div class="guidance">${escapeHtml(g.text || '')} <span class="badge">${escapeHtml(g.severity || g.priority || '')}</span></div>`)
    .join('');

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 24px; color: #111; font-size: 14px; line-height: 1.5; }
    h1 { font-size: 20px; margin-bottom: 8px; }
    .score { display: inline-block; width: 48px; height: 48px; border-radius: 24px; border: 3px solid ${scoreColor}; text-align: center; line-height: 42px; font-weight: 700; color: ${scoreColor}; margin-bottom: 16px; }
    .section { margin-top: 20px; }
    .section h2 { font-size: 16px; margin-bottom: 8px; color: #374151; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th, td { border: 1px solid #e5e7eb; padding: 8px 12px; text-align: left; }
    th { background: #f9fafb; font-weight: 600; }
    .block { margin: 12px 0; padding: 12px; background: #f9fafb; border-radius: 8px; border-left: 4px solid #3b82f6; }
    .guidance { margin: 8px 0; padding: 8px 0; border-bottom: 1px solid #eee; }
    .badge { font-size: 11px; color: #6b7280; }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <div class="score">${score}</div>
  <div class="section">
    <h2>Summary</h2>
    <p>${escapeHtml(summary)}</p>
  </div>
  ${parties.length ? `<div class="section"><h2>Parties</h2><table><tr><th>Name</th><th>Role</th></tr>${partiesHtml}</table></div>` : ''}
  ${contractAmount ? `<div class="section"><h2>Contract amount</h2><p>${escapeHtml(contractAmount)}</p></div>` : ''}
  ${payments.length ? `<div class="section"><h2>Payments</h2><table><tr><th>Label</th><th>Amount</th></tr>${paymentsHtml}</table></div>` : ''}
  ${keyDates.length ? `<div class="section"><h2>Key dates</h2><table><tr><th>Date</th><th>Label</th></tr>${keyDatesHtml}</table></div>` : ''}
  ${redFlags.length ? `<div class="section"><h2>Red flags &amp; risks</h2>${redFlagsHtml}</div>` : ''}
  ${guidance.length ? `<div class="section"><h2>Guidance</h2>${guidanceHtml}</div>` : ''}
  <p style="margin-top: 24px; font-size: 12px; color: #9ca3af;">Generated by AI Lawyer</p>
</body>
</html>`;
}

/**
 * Export current analysis to PDF and open share sheet.
 * @param {Object} analysis - analysis object (summary, documentType, score, redFlags, guidance, etc.)
 * @param {{ dialogTitle?: string }} options - optional; dialogTitle for the share sheet
 * @returns {Promise<string>} PDF file URI
 */
export async function exportAnalysisToPdf(analysis, options = {}) {
  const { dialogTitle = 'Export analysis as PDF' } = options;
  const html = buildHtml(analysis);
  const { uri } = await Print.printToFileAsync({
    html,
    base64: false,
  });
  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle,
    });
  }
  return uri;
}
